### ISSUE TITLE
No puedo habilitar el plug-in

### ISSUE THREAD

**Issue by Casanaura** [Cyber-Root0/Azuriom-MercadoPago#1]
Saludos,

Primero que nada, enhorabuena por realizar este complemento para Azuriom; verdaderamente ayudará a muchas comunidades de América Latina para el procesamiento de pagos mediante MercadoPago.

Sin embargo, no logro poder habilitar el plug-in.

**PHP:** 8.2
**Azuriom:** 1.1.5

**Error Log**
`[2023-10-18 20:24:34] production.ERROR: require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory at /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php:45)
[stacktrace]
#0 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): require_once('...')
#3 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Plugin\\Mercadopago\\Providers\\MercadopagoServiceProvider->register()
#4 /home/trappynet/web/trappy.net/public_html/app/Extensions/Plugin/PluginManager.php(102): Illuminate\\Foundation\\Application->register()
#5 /home/trappynet/web/trappy.net/public_html/app/Providers/ExtensionServiceProvider.php(24): Azuriom\\Extensions\\Plugin\\PluginManager->loadPlugins()
#6 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Providers\\ExtensionServiceProvider->register()
#7 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#8 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\ProviderRepository->load()
#9 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#10 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(261): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#11 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#12 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#14 /home/trappynet/web/trappy.net/public_html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#15 /home/trappynet/web/trappy.net/public_html/server.php(19): require_once('...')
#16 {main}
"} 
[2023-10-18 20:24:55] production.ERROR: require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory at /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php:45)
[stacktrace]
#0 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): require_once('...')
#3 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Plugin\\Mercadopago\\Providers\\MercadopagoServiceProvider->register()
#4 /home/trappynet/web/trappy.net/public_html/app/Extensions/Plugin/PluginManager.php(102): Illuminate\\Foundation\\Application->register()
#5 /home/trappynet/web/trappy.net/public_html/app/Providers/ExtensionServiceProvider.php(24): Azuriom\\Extensions\\Plugin\\PluginManager->loadPlugins()
#6 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Providers\\ExtensionServiceProvider->register()
#7 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#8 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\ProviderRepository->load()
#9 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#10 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(261): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#11 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#12 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#14 /home/trappynet/web/trappy.net/public_html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#15 /home/trappynet/web/trappy.net/public_html/server.php(19): require_once('...')
#16 {main}
"} 
[2023-10-18 20:25:05] production.ERROR: require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): require_once(/home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/../../vendor/autoload.php): Failed to open stream: No such file or directory at /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php:45)
[stacktrace]
#0 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/trappynet/web/trappy.net/public_html/plugins/mercadopago/src/Providers/MercadopagoServiceProvider.php(45): require_once('...')
#3 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Plugin\\Mercadopago\\Providers\\MercadopagoServiceProvider->register()
#4 /home/trappynet/web/trappy.net/public_html/app/Extensions/Plugin/PluginManager.php(102): Illuminate\\Foundation\\Application->register()
#5 /home/trappynet/web/trappy.net/public_html/app/Providers/ExtensionServiceProvider.php(24): Azuriom\\Extensions\\Plugin\\PluginManager->loadPlugins()
#6 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Azuriom\\Providers\\ExtensionServiceProvider->register()
#7 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#8 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\ProviderRepository->load()
#9 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#10 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(261): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#11 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#12 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /home/trappynet/web/trappy.net/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#14 /home/trappynet/web/trappy.net/public_html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#15 /home/trappynet/web/trappy.net/public_html/server.php(19): require_once('...')
#16 {main}
"} 
`

**Comment by Cyber-Root0** [comment]
Olá @Casanaura ! Tudo bem? Espero que sim. Muito obrigado pelo retorno em relação ao plugin, necessariamente não é um erro. Mas sim está faltando instalar as dependências do plug-in para que funcione perfeitamente. Abra o diretório do plugin e dê o comando "composer update" pelo cmd/terminal. Abraços! Se precisar de mais ajuda pode me chamar em https://wa.me/5518981785298
